FROM dockerfile/nodejs
MAINTAINER Markus Dulghier <markus@dulghier.com>

RUN apt-get -y update && \
	apt-get -y install graphicsmagick

COPY package.json /app/
RUN npm install
COPY . /app

WORKDIR /app

CMD ["node", "--abort-on-uncaught-exception", "server.js"]

EXPOSE 8080
